[package]
name = "noodle-rating-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# openai_api_rust = "0.1.9"
rocket = "0.5.1"
rusqlite = { version = "0.35.0", features = ["bundled"] }
serde = "1.0.219"
serde_json = "1.0.140"
zstd = "0.13.3"
